---
site:
  title: "RHEL Image Mode Day 2 運用 | Red Hat Enterprise Linux Interactive Labs"
  url: https://tnk4on.github.io/zt-image-mode-day2
  start_page: modules::01-switch-registries.adoc

content:
  sources:
    - url: ./
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/nookbag-bundle/releases/download/v0.0.3/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
