---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-switch-registries"
      label: "レジストリの切り替え"
      solveButton: true
    - name: "02-switch-an-image"
      label: "イメージの切り替え"
      solveButton: true
    - name: "03-rollback-a-host"
      label: "ホストのロールバック"
      solveButton: true
    - name: "04-move-httpd-in-image"
      label: "httpd のイメージ内移行"
      solveButton: true

tabs:
  - name: ">_ Builder"
    url: /wetty/ssh/root
  - name: ">_ Image mode host"
    url: /wetty_imrhel/ssh/root
