= イメージの切り替え

== タグについて
この演習では `Builder` タブに戻ってください。

おさらいとして、コンテナイメージの命名規則は `registry/name:tag` です。このホスト上にある異なるイメージを確認してみましょう。

[source,bash,run]
----
podman images
----

前の演習では、RHEL 10 バージョンの新しいイメージをビルドする際に `el10` タグを使用しました。他のイメージでも TAG 列にバージョン情報が表示されています。ただし、他のラボでは明示的なタグを設定しなかったため、`podman` はデフォルトの `latest` タグを使用します。これは便利ですが、多くの混乱を招くことがあります。その `latest` コンテナには何が入っているのでしょうか？どの更新を提供したのでしょうか？これまでの `bootc status` の出力で `latest` タグを見たことがありますか？

== タグを使用したイメージ内容の識別

アプリケーションのデプロイに備えて、Web サーバーに新しいコンテンツを追加し、新しいタグでビルドしましょう。

vim を使ってファイルの末尾に以下の行を追加してください：

[source,bash,run]
----
vim Containerfile
----

[source,dockerfile]
----
RUN echo "New application coming soon!" > /var/www/html/index.html
----


== podman を使用したイメージのビルド

Containerfile の変更を保存したら、`+podman build+` を実行して新しいイメージを取得します。今回は、コンテナ名の末尾に `+v2+` を追加して特定のタグを設定します。コンテナツールは再び既存のレイヤーを再利用し、新しい Web ページ用に1つだけレイヤーを追加します。

[source,bash,run,subs=attributes+]
----
podman build -t registry-{guid}.{domain}/test-bootc:v2 .
----

== 複数のタグ付きバージョンのレジストリへのプッシュ

タグは人に情報を伝えるものであり、コンテナツールに伝えるものではありません。ツールは操作を行う際にタグに関連付けられた ID を使用します。つまり、タグを使用してユーザーに異なる種類の情報を伝えることができます。

例えば、このイメージが本番環境用ではなく開発環境用であることも知らせたいとしましょう。`+podman image tag+` サブコマンドで新しいイメージに `+dev+` タグを追加できます。このタグはローカルにのみ適用されるため、レジストリにもプッシュする必要があります。

[source,bash,run,subs=attributes+]
----
podman image tag registry-{guid}.{domain}/test-bootc:v2 registry-{guid}.{domain}/test-bootc:dev
----

作成したさまざまなイメージを確認しましょう。

[source,bash,run]
----
podman images test-bootc
----

3つのイメージがリストされていますが、`+IMAGE ID+` 列をよく見ると、そのうち2つは同じであることがわかります。

このラボ環境で利用可能なものよりも高度なツールを使えば、タグによる柔軟性は非常に強力なものになります。

更新されたイメージを使用可能にするために、レジストリにプッシュする必要があります。`+dev+` タグのイメージは、他のすべてのレイヤーが `+v2+` イメージと同一であるため、設定レイヤーのみをコピーすることに注目してください。

[source,bash,run,subs=attributes+]
----
podman push registry-{guid}.{domain}/test-bootc:v2
----

[source,bash,run,subs=attributes+]
----
podman push registry-{guid}.{domain}/test-bootc:dev
----

== v2 イメージへの切り替え

`Image mode host` タブに切り替えて更新を適用します。

レジストリにプッシュした新しいイメージは `+el10+` タグを使用していないため、`+bootc+` では更新として認識されません。

[source,bash,run]
----
bootc upgrade --check
----

タグはイメージ名の一部であるため、新しい `+v2+` イメージは `+bootc+` が追跡しているイメージとは異なるイメージです。最初の演習でリポジトリを変更した時と同様に、`+bootc switch+` を使用してインストールできます。同じイメージを参照する2つのタグがあるため、`+v2+` か `+dev+` のどちらでも新しいイメージをインストールできます。

[source,bash,run,subs=attributes+]
----
bootc switch registry-{guid}.{domain}/test-bootc:v2
----

最初の演習とは異なり、`+bootc switch+` は更新された1つのレイヤーのみをプルダウンします。

`+bootc switch+` を使用すると、起動したイメージとは異なるイメージが必要で、単純な更新ではないさまざまなシナリオを処理できます。Java JDK のようなコアアプリケーションコンポーネントのアップグレードテストを、アプリケーション用の新しいベースイメージを提供して行うことができます。あるいは、ホスト情報を維持したまま OS 全体をアップグレードテストすることもできます。これについては後ほど少し詳しく見ていきます。

変更を適用するにはシステムの再起動が必要です。

[source,bash,run]
----
reboot
----

== VM が v2 イメージで動作していることの確認

システムの再起動が完了したら、Refresh ボタンをクリックしてログインし直せます。

`+bootc status+` の `+spec+` セクションが更新先について何を表示しているか確認しましょう。

[source,bash,run]
----
bootc status | grep spec: -A 4
----

`+v2+` タグが確認できました。では、新しいプレースホルダーの index ページはどうでしょうか？

[source,bash,run]
----
curl localhost
----

[source,bash,run]
----
ls -alh /var/www/html/index.html
----

新しい index は表示されず、ディスク上にもありません。はい、手順には意図的なエラーがあります。これは、bootc が変更中にディレクトリとイメージの内容をどのように扱うかに基づく予想される動作です。

次の演習でこの問題を調査するため、VM にログインしたままにしてください。
