== 変更のロールバック

Image mode のシステムには、パッケージモード操作ではより多くの準備が必要となる機能がネイティブで備わっています：ロールバックです。

`+bootc+` はイメージをローカルに展開するため、ホストの以前のバージョンがディスク上にまだ残っています。`+v2+` イメージは元のイメージの横に展開され、ブートローダーのプライマリターゲットとして設定されました。パッケージモードのシステムで以前のバージョンを復元するには、変更前にスナップショットを設定するか、外部バックアップを参照する必要があります。`+bootc+` では、最後に起動したイメージに戻す単一のコマンドがあります。

Web ページが見つからないというのは、通常バックアップから復元が必要な問題ではありませんが、これはラボですので。ロールバックオプションが利用可能かどうか確認して、以前のイメージに戻しましょう。

[source,bash,run]
----
bootc status
----

ステータス出力の下部セクションに、利用可能なイメージターゲットが表示されます。`+v2+` タグなしの元のイメージが表示されるはずです。ロールバックをトリガーするには、1つのコマンドを実行します。

[source,bash,run]
----
bootc rollback
----

ロールバックが準備され、ブートローダーが更新されると、コマンドは次のように返すはずです：

[source,nocopy]
----
Next boot: rollback deployment
----

次回の起動で何が起こるかについて、ステータスの他の2つの箇所で確認できます。`+rollbackQueued+` の値が更新されているはずです。これはシステムの再起動前に確認するのに便利です。

[source,bash,run]
----
bootc status | grep Queued
----

[source,nocopy]
----
rollbackQueued: true
----

spec ブロックの起動順序を確認して、ブートローダーに送信された内容を確認することもできます。これは `+default+` または `+rollback+` のいずれかに一致するはずです。`+default+` の順序は、ステータスの `+spec+` セクションのイメージを使用します。

[source,bash,run]
----
bootc status | grep Order
----

[source,nocopy]
----
bootOrder: rollback
----

先に進む前に、`+bootc status+` をさらに自由に確認してください。

通常どおり、変更を適用するには再起動が必要です。再起動後、ロールバックイメージが起動イメージとなり、起動順序の新しいデフォルトにもなります。

[source,bash,run]
----
reboot
----

システムが再起動して以前の状態に戻っている間に、Containerfile で何が起こったのか、なぜ index.html の更新が期待どおりにいかなかったのかを詳しく調べてみましょう。
