== index ファイルに何が起きたのか？

新しい index.html ファイルに何が起きたのかを調べるには、`Builder` タブに戻ってください。

イメージを作成した際の `+podman build+` ではエラーが表示されなかったので、イメージ内で何が起きたのでしょうか？

bootc イメージは標準的な OCI イメージでもあるため、イメージをローカルコンテナとして実行することで変更をテストできます。標準的なコンテナツールにより、完全にインストールすることなくホストを反復確認・検査する新しい方法が得られます。

コンテナを起動してディレクトリの内容を一覧表示しましょう。対話的に実行してシェルを接続する代わりに、実行したいコマンドを引数としてコンテナに渡すだけです。`+ls+` コマンドを実行するコンテナが終了後に削除されるように `+--rm+` フラグも追加しています。

[source,bash,run,subs=attributes+]
----
podman run --rm registry-{guid}.{domain}/test-bootc:v2 ls /var/www/html
----
....
index.html
....

== イメージとホストの状態

ファイルはあるのに、なぜホスト上に表示されなかったのでしょうか？https://www.redhat.com/en/introduction-to-image-mode-for-red-hat-enterprise-linux-interactive-lab[image mode 入門ラボ,window=_blank]で、image mode における `+/etc+` の扱い方について説明しました。`+/var+` の階層も特別に扱われます。

[cols=",,",options="header",]
|===
|ディレクトリ |所有者 |bootc のアクション
|/usr |イメージ |上書き
|/etc |ホスト |マージ
|/var |ホスト |無視
|===

`+/var+` ディレクトリは、`+bootc+` によってホストのローカル状態として制御されると見なされます。ビルド時に Web コンテンツを管理してイメージでバージョン管理したい場合、`+bootc+` が制御する場所に移動する必要があります。

== イメージでファイルをバージョン管理する

新しい Containerfile を見て、その方法を確認しましょう。`+heredoc+` 形式で複数行をラップする新しい `+RUN+` コマンドに注目してください。

[source,bash,run]
----
cat Containerfile.index
----
[source,dockerfile,nocopy]
----
FROM registry.redhat.io/rhel10/rhel-bootc:10.1 

ADD etc /etc 

RUN dnf install -y httpd 
RUN systemctl enable httpd

RUN echo "New application coming soon!" > /var/www/html/index.html

RUN <<EOF # <1>
    mv /var/www /usr/share/www # <2>
    sed -i 's-/var/www-/usr/share/www-' /etc/httpd/conf/httpd.conf
EOF
----
<1> `EOF` をデリミタとして使用する `heredoc` セクション
<2> `RUN` ディレクティブによって実行されるコマンド

ラボ以外では、`index.html` を作成する `echo` コマンドを別のレイヤーとして含めるのではなく、`heredoc` 内に入れるのが一般的です。`heredoc` は単一のレイヤーとなり、`&` 演算子でシェルコマンドを結合する代替手段です。

このブロックの最初のコマンドは、Apache によってインストールされたディレクトリとファイルを `+/usr+` 配下の新しいディレクトリに移動します。2番目のコマンドは、httpd の設定ファイルを更新して、デフォルトのドキュメントルートを新しいディレクトリに変更します。

bootc ホスト上でこの `+/etc+` 内のファイルに何も変更を加えていないため、この変更は `+bootc+` によって適用されます。httpd の設定にローカルの変更を加えていた場合は、ドロップインファイルを作成するか、他の方法で Apache の設定を更新する必要があるかもしれません。

== podman を使用したイメージのビルド

この新しいファイルを `+podman build+` コマンドに `-f` オプションで渡し、`+v3+` タグも付けます。このようなバージョニングのセマンティクスを追加することで、一連の更新されたイメージの中で最新のものを把握しやすくなります。

[source,bash,run,subs=attributes+]
----
podman build -t registry-{guid}.{domain}/test-bootc:v3 -f Containerfile.index
----

先ほどと同じ方法で、新しいファイルの場所をテストしましょう。コンテナをローカルで実行します。

[source,bash,run,subs=attributes+]
----
podman run --rm registry-{guid}.{domain}/test-bootc:v3 ls /usr/share/www/html
----

必要な変更があることを確認できたら、レジストリにプッシュできます。ここでも、ディレクトリの内容を変更して新しいタグを作成したにもかかわらず、変更されたレイヤーのみがレジストリに追加されることに注目してください。

[source,bash,run,subs=attributes+]
----
podman push registry-{guid}.{domain}/test-bootc:v3
----

== VM を最新バージョンに切り替え

この更新を適用するには、`Image mode host` タブに戻ってください。

他の演習と同様に、`+bootc switch+` を使用して、更新された Apache 設定を含む作成したイメージに変更できます。

[source,bash,run,subs=attributes+]
----
bootc switch registry-{guid}.{domain}/test-bootc:v3
----

新しいイメージが次回の起動用にステージングされていることを確認しましょう。

[source,bash,run]
----
bootc status
----

spec ブロックの起動順序を確認して、ブートローダーに送信された内容を確認できます。`+default+` に戻っていることに注目してください。

[source,bash,run]
----
bootc status | grep Order
----

では、最後にもう一度システムを再起動して変更を適用しましょう。

[source,bash,run]
----
reboot
----

システムの再起動が完了したら、`reconnect` をクリックするか、タブ名の横にある Refresh ボタンをクリックしてログインし直せます。

新しいプレースホルダーの index ページはどうでしょうか？

[source,bash,run]
----
curl localhost
----

イメージから制御される新しいドキュメントルートができました。この考え方は、ランタイムにホスト上で管理するのではなく、標準ビルドの一部として確実に含めたいソフトウェアやその他のコンテンツに使用できます。

これで、ホストが追跡するイメージの変更方法、ディレクトリ状態の違いに関するいくつかの洞察、そしてイメージ更新からのロールバック機能を探索しました。これは、独自に image mode をさらに探索するための良い基盤となるでしょう！
